# Generated by Django 2.2.10 on 2020-02-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sactive',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
