# Generated by Django 2.2.10 on 2020-02-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_patient_sactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='pres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50)),
                ('prid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dosage', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='name',
            new_name='prid',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
    ]
