# Generated by Django 2.2.10 on 2020-03-24 05:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20200228_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 24)),
        ),
        migrations.AlterField(
            model_name='pres',
            name='prid',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Prescription'),
        ),
    ]
